# Generated by Django 4.2.17 on 2025-02-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, upload_to='uploads/videolar/', verbose_name='Asosiy mavzu videosi')),
                ('presentation', models.FileField(blank=True, upload_to='uploads/presentations/', verbose_name='Taqdimot')),
                ('lesson_plan', models.FileField(blank=True, upload_to='uploads/dars_ishlanmalar/', verbose_name='Dars ishlanmalar')),
                ('word_theme', models.FileField(blank=True, upload_to='uploads/word_mavzular/', verbose_name='Word mavzular')),
                ('questions', models.FileField(blank=True, upload_to='uploads/nazorat_savollar/', verbose_name='Nazorat savollar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(max_length=255)),
                ('video_practice', models.FileField(blank=True, upload_to='uploads/videolar/', verbose_name='Amaliyot videosi')),
                ('presentation_practice', models.FileField(blank=True, upload_to='uploads/presentations/', verbose_name='Amaliyot taqdimoti')),
                ('lesson_plan_practice', models.FileField(blank=True, upload_to='uploads/dars_ishlanmalar/', verbose_name='Dars ishlanmalar amaliyot')),
                ('word_theme_practice', models.FileField(blank=True, upload_to='uploads/word_mavzular/', verbose_name='Word mavzular amaliyot')),
                ('questions_practice', models.FileField(blank=True, upload_to='uploads/nazorat_savollar/', verbose_name='Nazorat savollar amaliyot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='subject.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TestPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='subject.practice')),
            ],
        ),
        migrations.CreateModel(
            name='TestOptionPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='subject.testpractice')),
            ],
        ),
        migrations.CreateModel(
            name='TestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='subject.test')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_plan', models.FileField(blank=True, null=True, upload_to='uploads/kalendar_reja/')),
                ('author', models.ManyToManyField(related_name='subjects', to='subject.author')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='practice',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_practice', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='subject.subject'),
        ),
    ]
