# Generated by Django 4.2.17 on 2025-02-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='practice_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='practice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testoptionpractice',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_options', to='subject.testpractice'),
        ),
    ]
