# Generated by Django 4.2.17 on 2025-02-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_rename_practice_name_practice_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='description',
        ),
    ]
