# Generated by Django 4.2.17 on 2025-02-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_remove_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='outline',
            field=models.FileField(blank=True, null=True, upload_to='uploads/mundarija/'),
        ),
    ]
