# Generated by Django 4.2.17 on 2025-02-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_subject_outline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['created_at'], 'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['created_at'], 'verbose_name': 'Amaliyot', 'verbose_name_plural': 'Amaliyotlar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['created_at'], 'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['created_at'], 'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AlterModelOptions(
            name='testoption',
            options={'verbose_name': 'Variant', 'verbose_name_plural': 'Variantlar'},
        ),
        migrations.AlterModelOptions(
            name='testoptionpractice',
            options={'verbose_name': 'Amaliyot Testi Varianti', 'verbose_name_plural': 'Amaliyot Testi Variantilari'},
        ),
        migrations.AlterModelOptions(
            name='testpractice',
            options={'ordering': ['created_at'], 'verbose_name': 'Amaliyot Testi', 'verbose_name_plural': 'Amaliyot Testlari'},
        ),
    ]
